global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "15s"
rule_files:
  - "alert.yml"

scrape_configs:
  - job_name: "prometheus"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["prometheus:9090"]
    scheme: http
  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]
    scheme: http
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "kanban-app"
    static_configs:
      - targets: ["kanban-app:8080"]
  - job_name : "spring-actuator"
    static_configs:
      - targets: ["spring-actuator:8888"]
    metrics_path: /actuator/prometheus


  # - job_name: "kanban-app"
  #   static_configs:
  #       - targets: ["kanban-app:8080"]
  #   metrics_path: "/metrics"
  #   scheme: http

  

# alerting:
#   alertmanagers:
#     - scheme: http
#     - static_configs:
#         - targets: ['alertmanager:9093']
#             #- localhost:9093


