management:
  endpoints:
    web:
      actuator:
        enabled: true
        base-path: /actuator
        exposure:
          include: '*'
          metrics: true

  endpoint:
    prometheus:
      enabled: true
      metrics:
        enabled: true
        